import type { Metadata } from 'next';
import { useState } from 'react';
import { Inter } from 'next/font/google';

import './globals.css';
import { Header } from './components/header';
import { Drawer } from './components/drawer';
import { UIProvider } from '@/contexts/ui-context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Seishin Dreams',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='w-full h-[80px]' />
        <UIProvider>
          <Header />
          {children}
          <Drawer />
        </UIProvider>
      </body>
    </html>
  );
}
