import { IBook } from "./types"

export const coloringBookAnimalsData: IBook = {
	id: "B0CP64GV5B",
	title: "Animals",
	width: 233,
	height: 295,
	translationKey: "coloring_book_animals",
	pages: [
		{ src: "/books/coloring_book_animals/Cover.jpeg" },
		{ src: "/books/Empty-Page.jpeg" },
		{ src: "/books/coloring_book_animals/Title-Page.jpeg" },
		{ src: "/books/coloring_book_animals/Text-2.jpeg" },
		{ src: "/books/coloring_book_animals/Coloring-Page-2.jpeg" },
		{ src: "/books/coloring_book_animals/Text-3.jpeg" },
		{ src: "/books/coloring_book_animals/Coloring-Page-3.jpeg" },
		{ src: "/books/coloring_book_animals/Text-4.jpeg" },
		{ src: "/books/coloring_book_animals/Coloring-Page-4.jpeg" },
		{ src: "/books/coloring_book_animals/Text-5.jpeg" },
		{ src: "/books/coloring_book_animals/Coloring-Page-5.jpeg" },
		{ src: "/books/coloring_book_animals/Text-6.jpeg" },
		{ src: "/books/coloring_book_animals/Coloring-Page-6.jpeg" },
		{ src: "/books/coloring_book_animals/Text-7.jpeg" },
		{ src: "/books/coloring_book_animals/Coloring-Page-7.jpeg" },
		{ src: "/books/coloring_book_animals/Text-8.jpeg" },
		{ src: "/books/coloring_book_animals/Coloring-Page-8.jpeg" },
		{ src: "/books/coloring_book_animals/Text-9.jpeg" },
		{ src: "/books/coloring_book_animals/Coloring-Page-9.jpeg" },
		{ src: "/books/coloring_book_animals/Text-10.jpeg" },
		{ src: "/books/coloring_book_animals/Coloring-Page-10.jpeg" },
		{ src: "/books/coloring_book_animals/Text-11.jpeg" },
		{ src: "/books/coloring_book_animals/Coloring-Page-11.jpeg" },
		{ src: "/books/coloring_book_animals/Ending-Page.jpeg" },
		{ src: "/books/Empty-Page.jpeg" },
		{ src: "/books/coloring_book_animals/Back-Cover.jpeg" },
	],
}
